octokit/request.js

lib/http-error.js, test/request-test.js
=> error.status

package-lock.json, package.json, test/defaults-test.js, test/request-test.js
I noticed the following error when running `npm install`:
```
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
```
So I was wondering how the tests could work without the necessary dependency to `sinon`. Turns out sinon is not used by the tests so the dependency to `sinon-chai` can be removed.
=> test: remove unecessary dependency to `sinon-chai`

README.md, lib/http-error.js, lib/request.js, test/request-test.js
In case of an HTTP error, you can now inspect `error.request` to find out which request caused the problem
```js
request(options).catch(error => {
const {method, url} = error.request
console.error(`Error occurred for "${method} ${url}": ${error.message}`)
})
```
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/error-request/README.md)
=> error.request

README.md, lib/request.js, test/request-test.js
related: https://github.com/octokit/rest.js/issues/881
=> resolve with `url` property

README.md, lib/http-error.js, lib/request.js, test/request-test.js
closes #32, ref octokit/rest.js#1246
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/32-redact-credentials-in-error/README.md)
=> Redact credentials from error.request

lib/request.js
This would solve my issue in https://github.com/octokit/graphql.js/issues/20
fixes https://github.com/octokit/graphql.js/issues/20
=> Handle commonjs export in `is-plain-object`

src/types.ts
It is fully backwards compatible, since the default data type is still `any`
=> feat(typescript): Allow to pass on type information for response data

README.md, src/with-defaults.ts, test/request.test.ts
closes #71
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/request-hook-signature/README.md)
=> `options.request.hook`’s signature is now `(request, endpointOptions)`

src/types.ts, src/with-defaults.ts, test/request.test.ts
=> pass request-compatible API to `request.hook(request, options)`

README.md
Just noticed a few "ocotkit"s. 😅 🛠 
-----
[View rendered README.md](https://github.com/JamesMGreene/request.js/blob/patch-1/README.md)
=> Correct misspellings of Octokit in README

README.md
I tried the code snippet in the Authentication section and it didn't work. I changed it as shown in this commit and it worked. I assume that's the intended content?
-----
[View rendered README.md](https://github.com/orozcoadrian/request.js/blob/patch-1/README.md)
=> fix(README): typo in authentication section

package.json
works around the regression introduced with the bump from Typescript v3.7.5 to v3.9.3 in #137
=> fix(deps): pin typescript version due to #137

package.json
=> fix: bump minimal `node-fetch` version to `2.6.1` (security update)

README.md, src/fetch-wrapper.ts, test/request.test.ts
closes #322
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/332/log-deprecation-warnings/README.md)
=> feat: logs deprecation warning if `deprecation` header is present'

README.md, package-lock.json, package.json, src/fetch-wrapper.ts, test/request.test.ts
This pull request updates `@octokit/request-error` to `^2.1.0`, which introduces the `error.response` property.
`error.headers` is still set, but is now considered deprecated
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/error.response/README.md)
=> feat: `error.response`

README.md
The current docs do not make it explicit that the `Promise` returned from `request` is rejected on failure, so I reworded it to clarify that. Based on the following code:
https://github.com/octokit/request.js/blob/master/test/request.test.ts#L373-L391
https://github.com/octokit/request.js/blob/master/src/fetch-wrapper.ts#L100-L114
-----
[View rendered README.md](https://github.com/jakub-g/request.js/blob/patch-1/README.md)
=> doc: emphasize that failed requests result with rejected promise

README.md
Otherwise clicking the link doesn't go to the anchor.
-----
[View rendered README.md](https://github.com/nmattia/request.js/blob/patch-1/README.md)
=> Fix link to "The data parameter"

.github/workflows/codeql-analysis.yml
Do not run codeql.yml for dependabot branches
https://github.com/octokit/plugin-paginate-rest.js/pull/376
=> ci(codeql): ignore on push events for dependabot branches

src/fetch-wrapper.ts
`fetch` API has landed in Node.js 18 (and is available in modern browsers, Deno, Clodflare, etc). Failover from native `fetch` to `node-fetch` makes us confident that there will be no issues  when `node-fetch` is removed (say in 2046).
A new pattern of testing is made possible: instead of creating new instances of `Octokit` in test cases (with different fetch mocks), I can simply stub `globalThis.fetch` in test cases using a same instance of `Octokit` (imported from non-test code).
In some rare cases, this PR may break existing code. But generally I think it is safe.
=> refactor: failover from native fetch to node-fetch

README.md
I’m sorry for leaving `README.md` out of sync in #481.
-----
[View rendered README.md](https://github.com/baoshan/octokit-request.js/blob/doc/README.md)
=> docs(readme): use native `fetch` API first

README.md, src/fetch-wrapper.ts, test/request.test.ts
This aims to address #362 and adds specific handling for `AbortError` being thrown during a request. In the present state of things, if a user were to pass an `AbortSignal` via `options.request.signal`, the resulting error gets lumped in with a generic `RequestError` and the fact that the request was aborted is obscured.
With the present changes, the `AbortError` is bubbled up (similarly to how `RequestError` instances thrown by `fetch` are) so that the user can handle it however they want.
I'm more than open to input if you have a better vision for what should be included in the error that's rethrown (i.e. if it should be wrapped the same way the catchall `RequestError` is) if simply bubbling up the `AbortError` isn't enough. Since request cancellation is intentional, I would expect that …
=> feat: special handling for `AbortError`

README.md
No issue for this doc adjustment
----
'Sensible defaults' in `README.md` talks about `headers.agent`
'Sensible defaults' in `README.md` talks about `headers['user-agent']`
----
* N/A
`Type: Documentation`
----
=> docs(readme): use 'user-agent' instead of 'agent' as 'header' option in 'Sentible defauls' section

README.md
Resolves #613
----
No documentation on how to set an `Agent` to `octokit.request` internal `fetch`.
Documentation on how to set an `Agent` to `octokit.request` internal `fetch`.
- https://github.com/octokit/octokit.js/discussions/2484#discussioncomment-6386080
- https://github.com/nodejs/undici/discussions/2167
----
* N/A
`Type: Documentation`
----
=> docs(readme): add example for using a custom Agent

README.md, package-lock.json, package.json, src/fetch-wrapper.ts, test/request.test.ts
This is currently more a poc than the final implementation.
Resolves #601 
----
*
*
*
----
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
=> feat: add parseSuccessResponseBody Option

src/fetch-wrapper.ts, test/request.test.ts
Resolves #616 
----
Not very clear error message when `fetch` implementation is missing
Improved error message when `fetch` implementation is missing
*
----
* N/A
`Type: Maintenance`
----
=> fix(fetch-wrapper): improve error message when 'fetch' implementation is not present

src/fetch-wrapper.ts, test/request.test.ts
Resolves #641
----
Network errors from undici are presented with "fetch failed" without showing the underlying cause that undici also presents.
Network errors now correctly propagate the 'cause' from undici
----
=> fix: surface 'cause' for undici network errors

src/fetch-wrapper.ts, test/request.test.ts
Resolves #644
I found in my testing that undici may surface the `cause` property as an Error rather than as a plain string. This meant this if block never got executed and we never bubbled up the actual cause.
Correctly handle `cause` as an Error or as a string, and bubble up the message from the Error, if present.
----
=> fix: `error.cause` from undici may be instance of Error

src/fetch-wrapper.ts, test/request.test.ts
Resolves https://github.com/octokit/request.js/issues/649
----
*  Customer seems to be having issues with deploying their pages site in GHES and the error via the output from the debug appears to be caused by octokit. Seems when we are getting the response data we might run into an issue where the body is empty and hence we can't parse it using `response.json()` causing the error to be raised.
```
##[debug]Evaluating condition for step: 'Deploy to GitHub Pages'
2##[debug]Evaluating: success()
3##[debug]Evaluating success:
4##[debug]=> true
5##[debug]Result: true
6##[debug]Starting: Deploy to GitHub Pages
7##[debug]Loading inputs
8##[debug]Evaluating: github.token
9##[debug]Evaluating Index:
10##[debug]..Evaluating github:
11##[debug]..=> Object
12##[debug]..Evaluating String: …
```
=> fix: avoid `Unexpected end of JSON input` when response body is empty

package-lock.json, package.json, src/fetch-wrapper.ts, src/is-plain-object.ts, test/is-plain-object.test.ts
Fixes https://github.com/octokit/core.js/issues/519
See also https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isplainobject
----
* 
* 
----
=> fix: integrate isPlainObject

package-lock.json, package.json, src/fetch-wrapper.ts, src/index.ts, src/with-defaults.ts, test/defaults.test.ts, test/is-plain-object.test.ts, test/request.test.ts, test/tsconfig.test.json
This PR replaces NodeJS internal module imports with `node:` specifier imports.
=> refactor: use `node:` specifier imports and full relative paths imports, update tests for new type errors

test/request.test.ts
----
* Polyfills meant for older versions of Node were present
* Removes those unneeded polyfills
----
=> test: remove `AbortController` and `AbortSignal` polyfills

README.md, package-lock.json, package.json, scripts/build.mjs, src/fetch-wrapper.ts, test/request.test.ts, test/tsconfig.test.json, tsconfig.json
BREAKING CHANGE: Output a single ESM bundle
=> feat: switch to ESM output

README.md
No issue for this doc adjustment
----
code examples in `README.md` use CommonJS
code examples in `README.md` use ESM
----
* N/A
`Type: Documentation`
----
=> docs(readme): examples use ESM

.github/workflows/release.yml
----
* While introducing provenance to this repo in #685, the `permissions` key in the workflow was duplicated
* Removes the duplicated permissions key
----
=> ci(release): remove duplicate permissions entry

scripts/build.mjs
Resolves octokit/core.js#667 
Resolves octokit/core.js#665
Partly reverts #681
---
- Some consumers of this package could not resolve it properly (ex: `jest`, `ts-node`, `tsx`)
- CJS consumers would be getting errors even though the package is ESM
- Clients should be able to import the module without any errors with the fallback
- CJS consumers will generate a better error with the new fallback
---
=> fix(pkg): add `default` fallback to exports

test/request-common.test.ts
=> chore(test): remove fetch-mock from request-common-test.ts

src/fetch-wrapper.ts
We can assign directly fetch once. Probably we originally did this this way to keep the type of fetch. But this simplifies the code.
I will provide multiple PRs for this package, to avoid a big convoluted PR with various changes.
Also creating them as chores, to avoid releasing a new version every time it would be merged.
=> refactor: assign fetch once

package-lock.json, package.json, src/fetch-wrapper.ts, test/mock-request-http-server.ts, test/request-native-fetch.test.ts, test/request.test.ts
Use async await for better readability.
=> fix(refactor): async await instead of Promise chain

package-lock.json, package.json, src/fetch-wrapper.ts, test/request-common.test.ts, test/request-native-fetch.test.ts, test/request.test.ts
first #711 should be merged, than I want to see if there is some aspects regarding resilience.
=> chore: improve getResponseData

package-lock.json, package.json
See https://github.com/octokit/octokit.js/issues/2762#issuecomment-2486997620
----
* Types would include a reference to `@types/node` even though there is nothing using Node specific APIs in the types
* Update `@octokit/types` to make sure types are platform agnostic
----
=> fix(deps): bump `@octokit/types` to fix deno compat

src/fetch-wrapper.ts, test/request.test.ts
GitHub has APIs that return `application/scim+json` response bodies. Currently, these responses are not parsed as JSON, and instead, an `ArrayBuffer` is returned in `response.data`.
This adds handling for `application/scim+json` so they are parsed as JSON as normal.
```js
import { Octokit } from "@octokit/rest";
import { enterpriseCloud } from "@octokit/plugin-enterprise-cloud";
const MyOctokit = Octokit.plugin(enterpriseCloud);
const myOctokit = new MyOctokit({
auth: "ghp_xxxxxxxx",
});
const resp = await myOctokit.request('GET /scim/v2/enterprises/{enterprise}/Groups', {
enterprise: 'fabrikam'
});
console.log(JSON.stringify(resp.data));
```
* Modify `getResponseData` function in `src/fetch-wrapper.ts` to include a check for `application/scim+json` content type.
* Refactor content type …
=> Correctly parse response bodies as JSON where the Content-Type is `application/scim+json`

package-lock.json, package.json, test/request.test.ts
This is a blocker for the release to get previous merged work shipped.
=> fix: linting issues

package-lock.json, package.json, src/fetch-wrapper.ts, test/request.test.ts
Backport of https://github.com/octokit/request.js/releases/tag/v9.2.2
Backport of https://github.com/octokit/request.js/releases/tag/v9.2.1
=> fix: ReDos regex vulnerability, reported by @DayShift

package.json
Resolves #764
Please note that since I don't have write access to this package on npm registry, `npx semantic-release --dry-run` [refused](https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun) to continue processing. So the fix is NOT fully tested.
----
* Got `var VERSION = "0.0.0-development";` in `dist-bundle/index.js`
* `0.0.0-development` should be replaced with the actual version number
----
=> fix(pkg): unreplaced version number in `dist-bundle/`
