package.json
follow up for https://github.com/octokit/rest.js/issues/824
=> don’t publish unnecessary files to npm

package-lock.json, package.json
Fixes #14
Signed-off-by: Lucian <lucian.buzzo@gmail.com>
=> fix: add missing node-fetch dependency

package-lock.json, package.json
=> merge.all is not a function

.travis.yml, README.md, lib/fetch.js, lib/request.js, test/defaults-test.js, test/request-test.js
closes #35 
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/35/options-request-fetch/README.md)
=> options.request.fetch

README.md, package-lock.json, package.json, test/defaults-test.js, test/request-test.js
closes #38
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/38/request-format-and-previews/README.md)
=> media type format and previews

index.js, package-lock.json, package.json
=> Greenkeeper/@octokit/endpoint 5.1.0

.travis.yml, package-lock.json, package.json
closes #62, closes #61, closes #60
=> update pika builders

.travis.yml, README.md, package.json
null
-----
[View rendered README.md](https://github.com/octokit/request.js/blob/pika-cdn/README.md)
=> use cdn.pika.dev

src/fetch-wrapper.ts, test/request.test.ts
Adding test for issue octokit/rest.js#1497
octokit/rest.js#1499
=> feat: add server validation errors to error message

package-lock.json, package.json
=> feat(TypeScript): types for all known types

package-lock.json, package.json, src/with-defaults.ts
=> fix(deps): update @octokit/types to version 2.11.1

test/request.test.ts
Issue #111: Add test for request timeout
=> test: request timeout

src/fetch-wrapper.ts
Follow up from https://github.com/octokit/request.js/pull/599#discussion_r1256271587.
=> fix: remove data argument

src/fetch-wrapper.ts
----
* The option `signal` would not get passed through as documented
* The `signal` option is now passed through correctly
*
----
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
----
=> fix: correct the passing of the `signal` option

src/fetch-wrapper.ts
Resolves #611 
----
* The `redirect` option was defined in the types, but wasn't passed through in the options
* The `redirect` option is properly passed through to fetch
*
----
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
----
=> fix(types): remove `redirect` option

src/fetch-wrapper.ts, test/request.test.ts
Resolves #666
----
* `RequestError [HttpError]: Resource not accessible by integration`
* `RequestError [HttpError]: Resource not accessible by integration - https://docs.github.com/rest/actions/workflow-runs#get-a-workflow-run`
> Changing the length or format of opaque strings (eg IDs, error messages, other human-readable strings)
----
=> Report documentation with error message

scripts/build.mjs
----
* Tooling could have some issues resolving the package
* Adds the `main` field to help resolve some of these issues
----
=> fix(pkg): add `main` export

src/fetch-wrapper.ts, src/get-buffer-response.ts
well, why did we extract that function? better reintegrate it :)
=> chore: integrate getBufferResponse

.github/workflows/test.yml
Relates to https://github.com/octokit/tsconfig/issues/29#issuecomment-2372295972
----
* We were not checking if a PR was introducing `lint` or `tsc` errors.
* We start checking if a PR introduces `lint` or `tsc` errors.
----
=> ci run build

package-lock.json, package.json
=> chore(deps): update dependency undici to v7 (#728)
